name: Feature Request 🫂
description: Suggest an idea or improvement.
assignees:
labels: ["Enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ### Share your idea! 💡
        Help us understand how to make Icons8-Collector better for everyone.

  - type: textarea
    id: problem_use_case
    attributes:
      label: 🧩 Problem / Use Case
      description: "What problem are you facing, or what gap are you trying to fill?"
      placeholder: "e.g., I need to [describe need]..."
    validations:
      required: true

  - type: textarea
    id: expected_output
    attributes:
      label: 📤 Proposed Feature / Behavior
      description: "What should happen once this feature is implemented?"
      placeholder: |
        Example:-
        [Describe the feature]
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives / Workarounds
      description: "Have you tried another way to achieve this? Why wasn’t it good enough?"
      placeholder: |
        e.g.,
        - Used manual download, but it’s slow
        - Tried a different script, but it lacks format options
        - Used another tool, but it doesn’t support batch mode
    validations:
      required: false
